version: "3"

services:
  database:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: partner-gis-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: partner-gis

  app:
    build:
      context: ./
    container_name: partner-gis-server
    command: /bin/sh -c "./wait && yarn start"
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      WAIT_HOSTS: database:3306
      WAIT_TIMEOUT: 60
    depends_on:
      - database
