version: "3"

services:
  database:
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: partner-gis-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: partner-gis
