name: Check

on:
  push:
    branches:
      - main
jobs:
  check:
    name: Lint Types Tests
    runs-on: ubuntu-latest
    steps:
      # checkout

      - name: Checkout
        uses: actions/checkout@v2

      # setup node

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # yarn cache

      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Config Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ hashFiles('**/yarn.lock') }}

      # deps
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # checks

      - name: Check Lint
        run: yarn lint

      # tests

      - name: Run Tests
        run: yarn test:unit

    